<?xml version="1.0"?>
<robot name="fourWD" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
	<xacro:arg name="with_cam" default="true" />
	<xacro:arg name="with_fisheyes" default="false" />
	<xacro:arg name="with_ydlidar" default="true" />

	<xacro:arg name="cam_x" default="0" />
	<xacro:arg name="cam_y" default="0" />
	<xacro:arg name="cam_z" default="0" />
	<xacro:arg name="cam_roll" default="0" />
	<xacro:arg name="cam_pitch" default="0" />
	<xacro:arg name="cam_yaw" default="0" />
	<xacro:arg name="cam_W" default="320" />
	<xacro:arg name="cam_H" default="240" />
	<xacro:arg name="cam_focal" default="3.6" />
	<xacro:arg name="cam_hfov" default="1.3962634" />
  <xacro:arg name="ydlidar_ray_max_range" default="0.50" />
<!-- above is not overwriting please check again : ydlidar_ray_max_range. may be change to arg-->

  <xacro:include filename="$(find catabot_gazebo_simulation)/urdf/differential_drive_base.urdf.xacro" /> 
  <xacro:include filename="$(find catabot_gazebo_simulation)/urdf/fisheyes.urdf.xacro" /> 
  <xacro:include filename="$(find catabot_gazebo_simulation)/urdf/ydlidar.urdf.xacro" /> 
  <xacro:include filename="$(find catabot_gazebo_simulation)/urdf/cam.urdf.xacro" /> 

<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="1.0 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="Yellow">
    <color rgba="0.0 1.0 1.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>


  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <property name="M_PI" value="3.1415926535897931" />
  <property name="M_PI_2" value="1.570796327" />
  <property name="M_PI_4" value="0.78539816339" />
  <property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Main body length, width and height -->
  <!-- Main Body Box base   -->
  <property name="base_length" value="0.22" /> 
  <property name="base_width" value="0.145" />
  <property name="base_height" value="0.09" /> 
  <property name="base_mass" value="0.7" /> <!-- in kg-->


  <!-- Wheels -->
  <property name="wheel_radius" value="0.032" /> 
  <property name="wheel_height" value="0.025" />
  <property name="wheel_mass" value="0.03" /> --> <!-- in kg-->
  

  <!-- Macro for calculating inertia of cylinder -->
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </macro>

<!-- Macro for calculating inertia of box -->
  <macro name="box_inertia" params="m l w h">
    <inertia  ixx="${m*(w*w+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(l*l+h*h)/12}" iyz = "0"
              izz="${m*(l*l+w*w)/12}" /> 
  </macro>


  <!-- here starts the real definition of the robot -->
	<differential_drive_base
		base_link="base_link"
		base_length="${base_length}"
		base_width="${base_width}"
		base_height="${base_height}"
		base_mass="${base_mass}"
		wheel_radius="${wheel_radius}"
		wheel_height="${wheel_height}"
		wheel_mass="${wheel_mass}"/>


	<xacro:if value="$(arg with_fisheyes)">
		<fisheyes parent="base_link" x="0" y="0" z="${base_height/2}" roll="0" pitch="0" yaw="0"/>
	</xacro:if>

	<xacro:if value="$(arg with_ydlidar)">
		<ydlidar parent="base_link" x="0" y="0" z="${base_height/2}" roll="0" pitch="0" yaw="0"/>
	</xacro:if>

	<xacro:if value="$(arg with_cam)">
		<cam parent="base_link"
			x="$(arg cam_x)"
			y="$(arg cam_y)"
			z="${$(arg cam_z)+base_height/2}"
			roll="$(arg cam_roll)"
			pitch="$(arg cam_pitch)"
			yaw="$(arg cam_yaw)"
			W="$(arg cam_W)"
			H="$(arg cam_H)"
			hfov="$(arg cam_hfov)"
			focal="$(arg cam_focal)"
		/>
			
	</xacro:if>

</robot>
